name: Create Update Reminder

on:
  schedule:
  - cron: "0 0 * * 0"
  
jobs:
  createUpdateReminder:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create issue to remind about updating dependencies
        id: ciff
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Update Dependencies Manually
          content-filepath: ./example-content/update-reminder.md
